spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mariadb://localhost:3306/qtw?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: eco_local
    password: eco_local
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
        globally_quoted_identifiers: true
        default_batch_fetch_size: 1000
        temp:
          use_jdbc_metadata_defaults: false
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
      host: 127.0.0.1
      port: 6379
      password: redis


# TRACE  <  DEBUG  <  INFO  <  WARN  <  ERROR
logging:
  level:
    org.hibernate:
      type.descriptor.sql: DEBUG
      SQL: DEBUG
  
token:
  expiration_time: 864000000 # 10 Days
  secret: user_token

gateway:
  ip: 192.168.0.100
