spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mariadb://localhost:3307/qtw?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: eco_local
    password: '{cipher}5d642b879f6365b2c2bf91513ba238bf4f07caa3edb8cf3bef849f362cfdf966'
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
        globally_quoted_identifiers: true
        default_batch_fetch_size: 1000
        temp:
          use_jdbc_metadata_defaults: false
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
      host: 127.0.0.1
      port: 6379
      password: redis
